export const weatherIconMappings: Record<string, string> = {
  // WMO code: icon name (day variant / night variant)
  "0": "day-sunny",
  "1": "day-sunny-overcast",
  "2": "day-cloudy",
  "3": "cloudy",
  "45": "fog",
  "48": "fog",
  "51": "sprinkle",
  "53": "sprinkle",
  "55": "rain",
  "56": "rain-mix",
  "57": "rain-mix",
  "61": "rain",
  "63": "rain",
  "65": "rain",
  "66": "rain-mix",
  "67": "rain-mix",
  "71": "snow",
  "73": "snow",
  "75": "snow",
  "77": "snow",
  "80": "showers",
  "81": "showers",
  "82": "rain",
  "85": "snow",
  "86": "snow",
  "95": "thunderstorm",
  "96": "storm-showers",
  "99": "storm-showers",
  // night variants
  "0n": "night-clear",
  "1n": "night-partly-cloudy",
  "2n": "night-alt-cloudy",
  "3n": "night-alt-cloudy",
  "45n": "night-fog",
  "48n": "night-fog",
}
